name: DOTD Data Collector

on:
  schedule:
    # Run every 30 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  collect-data:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write # Required to commit and push changes
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Fetch full history for proper git operations
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pytz
    
    - name: Create data directory
      run: mkdir -p dotd_data
    
    - name: Run DOTD collector
      run: python main.py
    
    - name: Configure git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    
    - name: Commit and push changes
      run: |
        git add dotd_data/
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update DOTD data - $(date -u +"%Y-%m-%d %H:%M UTC")"
          git push
        fi
